global_vars:
  - name: first_name
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_FIRST_NAME"
  - name: last_name
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_LAST_NAME"
  - name: full_name
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_FULL_NAME"
  - name: nationality
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_NATIONALITY"
  - name: birthday_world
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_BIRTHDAY_WORLD"
  - name: birthday_us
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_BIRTHDAY_US"
  - name: email
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_EMAIL"
  - name: phone
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_PHONE"
  - name: city
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_CITY"
  - name: address_location
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ADDRESS_LOCATION"
  - name: address_code
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ADDRESS_CODE"
  - name: address_detail
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ADDRESS_DETAIL"
  - name: link_github
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_LINK_GITHUB"
  - name: link_linkedin
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_LINK_LINKEDIN"
  - name: link_portfolio
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_LINK_PORTFOLIO"
  - name: link_massvocab
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_LINK_MASSVOCAB"
  - name: notice_period
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_NOTICE_PERIOD"
  - name: salary_usd
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_SALARY_USD"
  - name: salary_eur
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_SALARY_EUR"
  - name: id_self
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ID_SELF"
  - name: id_mom
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ID_MOM"
  - name: id_dad
    type: shell
    params:
      cmd: "source $HOME/Programming/JimmyTranDev/secrets/env.sh && echo $ESPANSO_ID_DAD"

matches:
  # happy
  - trigger: "/eha"
    replace: "(^.^)"
  # joyful
  - trigger: "/ehb"
    replace: "(*^▽^*)"
  # excited
  - trigger: "/ehc"
    replace: "(>_<)"
  # victory
  - trigger: "/ehd"
    replace: "٩(◕‿◕)۶"
  # peaceful
  - trigger: "/ehe"
    replace: "(✿◠‿◠)"
  # wholesome
  - trigger: "/ehf"
    replace: "(´｡• ᵕ •｡`)"

  # in love
  - trigger: "/ela"
    replace: "(｡♥‿♥｡)"
  # hug
  - trigger: "/elb"
    replace: "(づ｡◕‿‿◕｡)づ"

  # blushing
  - trigger: "/esa"
    replace: "(⁄ ⁄•⁄ω⁄•⁄ ⁄)"
  # wink
  - trigger: "/esb"
    replace: "^.~"

  # crying
  - trigger: "/eca"
    replace: "(T_T)"
  # tears
  - trigger: "/ecb"
    replace: "(;_;)"
  # sobbing
  - trigger: "/ecc"
    replace: "(╥﹏╥)"
  # puppy eyes
  - trigger: "/ecd"
    replace: "(´•ω•̥`)"
  # wailing
  - trigger: "/ece"
    replace: "｡ﾟ･ (>﹏<) ･ﾟ｡"

  # angry
  - trigger: "/eaa"
    replace: "(╬益´)"
  # table flip
  - trigger: "/eab"
    replace: "(╯°□°）╯︵ ┻━┻"
  # disapproval
  - trigger: "/eac"
    replace: "(눈_눈)"
  # side eye
  - trigger: "/ead"
    replace: "(￢_￢)"
  # middle finger
  - trigger: "/eae"
    replace: "凸(￣ヘ￣)"

  # cat
  - trigger: "/ema"
    replace: "(=^･ω･^=)"
  # bear
  - trigger: "/emb"
    replace: "ʕ•ᴥ•ʔ"
  # lenny
  - trigger: "/emc"
    replace: "( ͡° ͜ʖ ͡°)"
  # shrug
  - trigger: "/emd"
    replace: "¯\\_(ツ)_/¯"

  # despair kneeling
  - trigger: "/exa"
    replace: "orz"
  # sleeping
  - trigger: "/exb"
    replace: "(-_-)zzz"
  # apathy
  - trigger: "/exc"
    replace: "( -_ - )"
  # good grief
  - trigger: "/exd"
    replace: "┐('～` )┌"
  # dead
  - trigger: "/exe"
    replace: "(×_×)"

  # stunned
  - trigger: "/efa"
    replace: "(O_O;)"
  # dizzy
  - trigger: "/efb"
    replace: "(＠_＠)"
  # blank stare
  - trigger: "/efc"
    replace: "(⊙_⊙)"
  # jump scare
  - trigger: "/efd"
    replace: "∑(O_O;)"
  # dazed
  - trigger: "/efe"
    replace: "ヘ(°¬°)ノ"

  # looking away
  - trigger: "/esc"
    replace: "(・・ )"
  # cringe
  - trigger: "/esd"
    replace: "(＃＞＜)"
  # my bad
  - trigger: "/ese"
    replace: "(￣ω￣;)"
  # peeking
  - trigger: "/esf"
    replace: "壁||ω･)ｼﾞー"
  # shame
  - trigger: "/esg"
    replace: "( ._.)"

  # running away
  - trigger: "/eta"
    replace: "ε=ε=┌(;￣▽￣)┘"
  # throwing
  - trigger: "/etb"
    replace: "( ・_・)ノ⌒●"
  # come at me
  - trigger: "/etc"
    replace: "(っಠ‿ಠ)っ"
  # banzai
  - trigger: "/etd"
    replace: "＼(￣▽￣)／"
  # flexing
  - trigger: "/ete"
    replace: "ᕙ(⇀‸↼‶)ᕗ"

  # stressed
  - trigger: "/epa"
    replace: "(；⌣̀_⌣́)"
  # trembling
  - trigger: "/epb"
    replace: "(((＞＜)))"
  # can't watch
  - trigger: "/epc"
    replace: "(ノ_<。)"
  # calm down
  - trigger: "/epd"
    replace: "ヾ(°∇°*)"
  # frantic wave
  - trigger: "/epe"
    replace: "(＠_＠)ﾉ"

  # smug grin
  - trigger: "/ega"
    replace: "(￣∀￣)"
  # I see you
  - trigger: "/egb"
    replace: "(¬‿¬)"
  # mischievous smile
  - trigger: "/egc"
    replace: "(o´▽`o)"
  # evil plan
  - trigger: "/egd"
    replace: "(｀∀´)Ψ"
  # devious side eye
  - trigger: "/ege"
    replace: "(￢‿￢ )"

  # delicious
  - trigger: "/eda"
    replace: "(っ˘ڡ˘ς)"
  # tea
  - trigger: "/edb"
    replace: "(o^ ^o)旦"
  # hot food
  - trigger: "/edc"
    replace: "( ˘▽˘)っ♨"
  # drooling
  - trigger: "/edd"
    replace: "( ￣﹃￣)"
  # cheers
  - trigger: "/ede"
    replace: "(*^◇^)_旦"

  # peeking
  - trigger: "/ewa"
    replace: "|･ω･)"
  # peek and hide
  - trigger: "/ewb"
    replace: "|д･)ソ"
  # shady lurking
  - trigger: "/ewc"
    replace: "|_￣))"
  # brick wall peek
  - trigger: "/ewd"
    replace: "┬┴┬┴┤(･_├┬┴┬┴"

  # magic spell
  - trigger: "/ena"
    replace: "(ﾉ>ω<)ﾉ :｡･::･ﾟ'★,｡･::･ﾟ'☆"
  # facepalm
  - trigger: "/enb"
    replace: "(－‸ლ)"
  # ghost
  - trigger: "/enc"
    replace: "(G_G)"
  # wait a minute
  - trigger: "/end"
    replace: "(－.－)ノ\""

  - trigger: "/pf"
    replace: "{{first_name}}"
  - trigger: "/pl"
    replace: "{{last_name}}"
  - trigger: "/pn"
    replace: "{{full_name}}"
  - trigger: "/pN"
    replace: "{{nationality}}"
  - trigger: "/pbw"
    replace: "{{birthday_world}}"
  - trigger: "/pbu"
    replace: "{{birthday_us}}"
  - trigger: "/pe"
    replace: "{{email}}"
  - trigger: "/pp"
    replace: "{{phone}}"

  - trigger: "/ac"
    replace: "{{city}}"
  - trigger: "/al"
    replace: "{{address_location}}"
  - trigger: "/ap"
    replace: "{{address_code}}"
  - trigger: "/as"
    replace: "{{address_detail}}"

  - trigger: "/lg"
    replace: "{{link_github}}"
  - trigger: "/ll"
    replace: "{{link_linkedin}}"
  - trigger: "/lp"
    replace: "{{link_portfolio}}"
  - trigger: "/lm"
    replace: "{{link_massvocab}}"

  - trigger: "/jn"
    replace: "{{notice_period}}"
  - trigger: "/jsu"
    replace: "{{salary_usd}}"
  - trigger: "/jse"
    replace: "{{salary_eur}}"

  - trigger: "/is"
    replace: "{{id_self}}"
  - trigger: "/im"
    replace: "{{id_mom}}"
  - trigger: "/id"
    replace: "{{id_dad}}"
